23 quiz results
OksanaMir/naftee-coffee-shop pull request #29
Opened 2021-06-01 17:20 UTC by OksanaMir

2021-06-01 22:40 UTC, VVeRRa requested changes

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +              name="control-ref"
Please, return overwriten ID, it's important to have unique id for all elemets on the website, this component us rendered many times on the page

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
>                        id={`weight-select-${id}-overview`}
I think this id does not belong on the select, but only on the wrapper

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +                      options={
Deleted values for options are corect

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +            {weightSelect === 50
Deleted option is correct

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +            data-item-custom2-name="Method"
This deletion is all wrong

2021-06-01 22:40 UTC, VVeRRa commented on pages/faq.js
> +                    index={index}
Id is correct

2021-06-01 22:40 UTC, VVeRRa commented on pages/index.js
> +              </Carousel>
So we are leaving the carousel here?

2021-06-01 22:40 UTC, VVeRRa commented on components/form/forms/QuizForm.js
> +    switch (quizItemIndex) {
Where is number one? Please, don't use switch, use map data structure insteadinstead. Also, please, it would be better readable if we work with values than with indexes.

2021-06-01 22:40 UTC, VVeRRa commented on components/form/forms/QuizForm.js
> +  const text = <span>Title</span>;
Please, delete text and content variable

2021-06-01 22:40 UTC, VVeRRa commented on components/form/forms/QuizForm.js
> +                    // trigger={['click']}
Why is triger commented? Tooltips arw not changing thwir values on hover so ve cannot use hover ans must use click instead

2021-06-01 22:40 UTC, VVeRRa commented on components/form/forms/QuizForm.js
> +
Is it working? OFinished is not defined anywhere

2021-06-01 22:40 UTC, VVeRRa commented on components/form/forms/QuizForm.js
> +// ?quiz?.[quizItemIndex]
Please, delete these comments and also g{' '} abov div within Radio.Grpup.

What is the submit button for? Ot's calling sendAnswears on click, but this function is not doing anything

2021-06-01 22:40 UTC, VVeRRa commented on components/header/Header.js
> -            <div  className={`${styles.shoppingBasket}`} id="snipcartShoppingBasket">
Why ia this in backticks?

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +import { Form } from 'antd';
Why is inputMumber deleted?

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +  const [weightSelect, setWeightSelect] = useState(50);
Sasha wanted 250 as default value

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +    prices,
Why is prices redeclared and quantitweight deleted?

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> -  const { productData } = quantityWeight;
Why is this deleted?

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> -    setQuantity(value);
Why is this deleted? Also it should be an arrow function

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> -
Why is this deleted?

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> -                name="amount"
Why is this deleted?

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> -              ? productData?.[0]?.quantity
Why is this deleted?

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +                ? prices?.prices[0]
Same here

2021-06-01 22:40 UTC, VVeRRa commented on components/product/ProductOverView.js
> +          </button> */}
Why is it commented out?

2021-06-01 22:40 UTC, VVeRRa commented on pages/faq.js
> +                      ></span>
Self cloaing tag is corrwct

2021-06-02 10:02 UTC, OksanaMir commented on components/form/forms/QuizForm.js
> +
Not yet.

2021-06-02 10:02 UTC, OksanaMir commented on pages/index.js
> +              </Carousel>
As I understood Sasha, just for mobile.

2021-06-02 10:03 UTC, merged